# Generated by Django 5.2.9 on 2025-12-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_permission_allowed_for_moderator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='granted_at',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='reviews.permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.permission'),
        ),
    ]
